### ISSUE TITLE
NA

### ISSUE THREAD

**Issue by Tc2r1** [Tc2r1/Hacktoberfest_Interview_App#162]
[Click Here For Details](https://github.com/Tc2r1/Hacktoberfest_Interview_App/tree/master/Cheat_Sheets)

**Comment by komalsoni4** [comment]
please assign me

**Comment by Tc2r1** [comment]
@komalsoni4  if you read the details you'd know how to request assignment...

**Comment by komalsoni4** [comment]
!assign

**Comment by ninjadev64** [comment]
!assign
