### ISSUE TITLE
Feature: Create a github action to automate the assignment of issues using a "!assign" command tag. 

### ISSUE THREAD

**Issue by Tc2r1** [Tc2r1/Hacktoberfest_Interview_App#59]
### Is your feature request related to a problem? Please describe.

Problem is I'm just one maintainer and I want to help facilitate those who wish to contribute in a more timely manner. 

### Describe the solution you'd like

Create a github action to automate the assignment of issues using a "!assign" command tag.  Thus the first to comment with !assign to an issue would get assigned the issue.

**Comment by gdguesser** [comment]
Hello, could you please assign it to me?

**Comment by Tc2r1** [comment]
@gdguesser done

**Comment by Tc2r1** [comment]
@Tc2r1  this doesn't seem to be working for new people?
